# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    container_name: research_boilerplate_node
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    command: npm run dev

  postgres:
    image: postgres:14
    container_name: postgres_db_research_node
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: